name: drbills_exchange
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  amicons: ^1.0.1
  auto_route: ^11.1.0
  country_code_picker: ^3.4.1
  cupertino_icons: ^1.0.8
  dio: ^5.9.1
  dots_indicator: ^4.0.1
  equatable: ^2.0.8
  flutter:
    sdk: flutter
  flutter_rating_bar: ^4.0.1
  flutter_spinkit: ^5.2.2
  flutter_svg: ^2.2.3
  google_fonts: ^8.0.1
  hive_ce: ^2.19.3
  hive_ce_flutter: ^2.3.4
  intl: ^0.20.2
  pinput: ^6.0.2
  retrofit: ^4.9.2
  tuple: ^2.0.2
  uuid: ^4.5.2

dev_dependencies:
  auto_route_generator: ^10.4.0
  build_runner: ^2.11.0
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  hive_ce_generator: ^1.11.0


flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
  